openapi: "3.0.0"
info:
  title: OpenWeatherMap API
  version: 1.0.0
  description: Weather date API documentation
  
servers:
  - url: https://api.openweathermap.org/geo/1.0 
  
paths:
  /direct:
    get:
      summary: Forward Geocoding by City
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: city name (e.g., trichy)    
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Max results
        - name: appid
          in: query
          required: true
          schema:
            type: string
          description: Your API key  
      responses:
        '200':
          description: Successful response
        '401':
          description: Invalide API key
  /reverse:
    get:
      summary: Forward Geocoding by City
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude    
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude
        - name: appid
          in: query
          required: true
          schema:
            type: string
          description: Your API key  
      responses:
        '200':
          description: Successful response
        '401':
          description: Invalide API key
    
          
          
          
          
          
          
          
          
          
          
          
